Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# Features can contain version numbers
Style/ClassAndModuleCamelCase:
  Exclude:
    - '**/definitions/**/*'
    - 'test/support/additional_definitions/**/*'

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'lib/foreman_maintain/system_helpers.rb'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Enabled: false

# Ruby 1.8.7
Style/EachWithObject:
  Enabled: false

